# coding: utf-8

"""
    Social Graph API

    Pho Networks REST API

    OpenAPI spec version: 1.1.1
    Contact: emre@phonetworks.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import pho_client
from pho_client.rest import ApiException
from pho_client.models.inline_response_200_1 import InlineResponse2001


class TestInlineResponse2001(unittest.TestCase):
    """ InlineResponse2001 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001(self):
        """
        Test InlineResponse2001
        """
        model = pho_client.models.inline_response_200_1.InlineResponse2001()


if __name__ == '__main__':
    unittest.main()
