# coding: utf-8

"""
    Social Graph API

    Pho Networks REST API

    OpenAPI spec version: 1.1.1
    Contact: emre@phonetworks.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InlineResponse2003In(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, _5f9e769ff6fe4cee02b3b4547200db6b=None):
        """
        InlineResponse2003In - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            '_5f9e769ff6fe4cee02b3b4547200db6b': 'NodeEdge'
        }

        self.attribute_map = {
            '_5f9e769ff6fe4cee02b3b4547200db6b': '5f9e769ff6fe4cee02b3b4547200db6b'
        }

        self.__5f9e769ff6fe4cee02b3b4547200db6b = _5f9e769ff6fe4cee02b3b4547200db6b


    @property
    def _5f9e769ff6fe4cee02b3b4547200db6b(self):
        """
        Gets the _5f9e769ff6fe4cee02b3b4547200db6b of this InlineResponse2003In.


        :return: The _5f9e769ff6fe4cee02b3b4547200db6b of this InlineResponse2003In.
        :rtype: NodeEdge
        """
        return self.__5f9e769ff6fe4cee02b3b4547200db6b

    @_5f9e769ff6fe4cee02b3b4547200db6b.setter
    def _5f9e769ff6fe4cee02b3b4547200db6b(self, _5f9e769ff6fe4cee02b3b4547200db6b):
        """
        Sets the _5f9e769ff6fe4cee02b3b4547200db6b of this InlineResponse2003In.


        :param _5f9e769ff6fe4cee02b3b4547200db6b: The _5f9e769ff6fe4cee02b3b4547200db6b of this InlineResponse2003In.
        :type: NodeEdge
        """
        if _5f9e769ff6fe4cee02b3b4547200db6b is None:
            raise ValueError("Invalid value for `_5f9e769ff6fe4cee02b3b4547200db6b`, must not be `None`")

        self.__5f9e769ff6fe4cee02b3b4547200db6b = _5f9e769ff6fe4cee02b3b4547200db6b

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
